import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const sackers_gothic_std_2 = localFont({
  src: '../../public/fonts/sackers-gothic-std 2.otf',
  variable: '--font-sackers-gothic-2',
});

const sackers_gothic_std_3 = localFont({
  src: '../../public/fonts/sackers-gothic-std 3.otf',
  variable: '--font-sackers-gothic-3',
});

const sackers_gothic_std_heavy = localFont({
  src: '../../public/fonts/sackers-gothic-std-heavy.otf',
  variable: '--font-sackers-gothic-heavy',
});

const sackers_gothic_std_light = localFont({
  src: '../../public/fonts/sackers-gothic-std-light.otf',
  variable: '--font-sackers-gothic-light',
});

const sackers_gothic_std = localFont({
  src: '../../public/fonts/sackers-gothic-std.otf',
  variable: '--font-sackers-gothic',
});

const SaolDisplay_light = localFont({
  src: '../../public/fonts/SaolDisplay-Light.ttf',
  variable: '--font-saol-display-light',
});

const SaolDisplay_light_italic = localFont({
  src: '../../public/fonts/SaolDisplay-LightItalic.ttf',
  variable: '--font-saol-display-light-italic',
});

const SaolDisplay_regular = localFont({
  src: '../../public/fonts/SaolDisplay-Regular.ttf',
  variable: '--font-saol-display-regular',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// This is how to use LocalFont in the code:
// classname={'font-[family-name:var(--font-sackers-gothic-heavy)]'}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang='fr'
      className={`
        ${sackers_gothic_std_2.variable}
        ${sackers_gothic_std_3.variable}
        ${sackers_gothic_std_heavy.variable}
        ${sackers_gothic_std_light.variable}
        ${sackers_gothic_std.variable}
        ${SaolDisplay_light.variable}
        ${SaolDisplay_light_italic.variable}
        ${SaolDisplay_regular.variable}
      `}
    >
      <body>{children}</body>
    </html>
  );
}
